import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Keep fonts if needed, or remove later
import "./globals.css";
import Layout from "@/components/Layout"; // Import the Layout component
import ThemeRegistry from "@/components/ThemeRegistry"; // Import the ThemeRegistry

const geistSans = Geist({ // Keep fonts for now
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry> {/* Wrap Layout with ThemeRegistry */}
          <Layout>{children}</Layout>
        </ThemeRegistry>
      </body>
    </html>
  );
}
